### ISSUE TITLE
Upload artifacts to Maven Central

### ISSUE THREAD

**Issue by keyboardr** [h6ah4i/android-verticalseekbar#19]
JCenter is being [sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Please upload artifacts to Maven Central by May 1st.

**Comment by h6ah4i** [comment]
@keyboardr 

Hi. I have managed to move all artifacts to Maven Central. :tada: 

https://repo1.maven.org/maven2/com/h6ah4i/android/widget/verticalseekbar/verticalseekbar/

**Comment by keyboardr** [comment]
Woohoo 🎉
