### ISSUE TITLE
How do I cange the thickness of the Vertical seekbar?

### ISSUE THREAD

**Issue by aribhatt91** [h6ah4i/android-verticalseekbar#2]

**Comment by h6ah4i** [comment]
@salvator91 Hi. Just specify `style` to `VerticalSeekBar`, it is the same as how to style normal `SeekBar`.

ref.) http://stackoverflow.com/questions/16163215/android-styling-seek-bar

**Comment by BlackReaper94** [comment]
what about the thickness of the onProgressChanged region?

It doesn't react to thickness in xml. Its hard to hit it with the a finger.
