### ISSUE TITLE
Drag handle goes outside layout bounds

### ISSUE THREAD

**Issue by AOrobator** [h6ah4i/android-verticalseekbar#5]
When the seekbar is in a LinearLayout with a specified weight, the drag handle is able to be dragged outside of the seekbar's layout bounds. Here is a sample repo that reproduces this issue 100% of the time: https://github.com/AOrobator/VerticalSeekbarBug

**Comment by h6ah4i** [comment]
@AOrobator Thanks for the issue report. I will take it a look.

**Comment by h6ah4i** [comment]
@AOrobator Hi. I have fixed the issue in the develop branch code. Could you try this via JitPack? I am going to release it as v0.7.1 after this issue is resolved. Thanks.

```gradle
repositories {
  maven { url "https://jitpack.io" }
}

dependencies {
  compile 'com.github.h6ah4i:android-verticalseekbar:c783941ef23a84e167ed72497472691730b51144'
}
```

**Comment by AOrobator** [comment]
Thanks! The fix works 👌🏾

**Comment by h6ah4i** [comment]
Thanks! I am going to reopen this and re-close it after v0.7.1 released.
