### ISSUE TITLE
Seekbars disappear with RTL layout direction

### ISSUE THREAD

**Issue by AOrobator** [h6ah4i/android-verticalseekbar#6]
The vertical seekbar disappears when the device is using an RTL layout direction. This is 100% reproducible and I don't believe this is Android version specific.

### Reproduction Steps

1. Open sample app included in this repository with normal LTR layout direction
2. Observe that vertical seekbars are visible
3. Change to RTL layout direction in developer settings by going to Settings > Developer Options > Drawing > Force RTL layout direction
4. Open sample app
5. Seekbars are no longer visible.

**Comment by h6ah4i** [comment]
Thanks, I'll take it a look.

**Comment by h6ah4i** [comment]
@AOrobator Hi. I've just released v0.7.2 and I believe the issue has been fixed 😄

**Comment by AOrobator** [comment]
I'm confirming that this issue is fixed. Thanks!
